services:
  pb-proposal:
    build: .
    container_name: pb-proposal-container
    restart: always
    ports:
      - "9999:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
    expose:
      - "80"
    networks:
      - infotickers-net

networks:
  infotickers-net:
    external: true
