services:
  mongo:
    image: mongo:8.0
    container_name: ecomm_mongo
    ports:
      - "28018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pbmnguser
      - MONGO_INITDB_ROOT_PASSWORD=P1n3c1092$
    volumes:
      - ./mongodb/data:/data/db

  #   redis:
  #     image: redis:7
  #     container_name: ecomm_redis
  #     profiles: [ "local" ]
  #     ports:
  #       - "6480:6379"

  #   rabbitmq:
  #     image: rabbitmq:3-management
  #     container_name: ecomm_rabbit
  #     profiles: [ "local" ]
  #     ports:
  #       - "5773:5672"
  #       - "16673:15672"
  #     environment:
  #       - RABBITMQ_DEFAULT_USER=mpbadmin
  #       - RABBITMQ_DEFAULT_PASS=Elverde.1978%
  #     volumes:
  #       - ./rabbitmq/data:/var/lib/rabbitmq

  backend:
    build: ./backend
    container_name: ecomm_backend
    depends_on:
      - mongo
      # - redis
      # - rabbitmq
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8090:8000"
    environment:
      - MONGO_URI=mongodb://pbmnguser:P1n3c1092$@mongo:27017
      - REDIS_URL=redis://redis:6379/0
      - RABBITMQ_URL=amqp://mpbadmin:Elverde.1978%25@rabbitmq:5672//
      - DATABASE_NAME=ecomm
    networks:
      - default
      - pbuniversity-net

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_BASE_PATH: /prjzdev1092
    container_name: ecomm_frontend
    ports:
      - "9090:3000"
    environment:
      - NEXT_PUBLIC_BASE_PATH=/prjzdev1092
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run start
    networks:
      - default
      - pbuniversity-net

  #   worker:
  #     build: ./backend
  #     container_name: ecomm_worker
  #     profiles: [ "local" ]
  #     command: [ "celery", "-A", "app.celery_worker.celery_app", "worker", "--loglevel=info" ]
  #     depends_on:
  #       - mongo
  #       - redis
  #       - rabbitmq
  #     volumes:
  #       - ./backend:/app
  #     environment:
  #       - MONGO_URI=mongodb://pbmnguser:P1n3c1092$@mongo:27017
  #       - REDIS_URL=redis://redis:6379/0
  #       - RABBITMQ_URL=amqp://mpbadmin:Elverde.1978%25@rabbitmq:5672//
  #       - DATABASE_NAME=ecomm

  haproxy:
    image: haproxy:2.4
    container_name: ecomm_haproxy
    profiles: [ "local" ]
    ports:
      - "80:80"
      - "443:443"
      - "9990:80" # Local access port
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy/certs:/usr/local/etc/haproxy/certs:ro
    depends_on:
      - backend
      - frontend

networks:
  default:
    name: ecomm-app_default
  pbuniversity-net:
    external: true
    name: pbuniversity-net
